config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Sessions

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Core application routes

  resources :projects, except: :destroy do
    member do
      get :about
      get :share, to: 'memberships#show'
    end
    # TODO: https://guides.rubyonrails.org/routing.html#limits-to-nesting
    resources :iterations do
      resources :check_ins do
        resources :check_in_ratings
      end
      resources :debriefs do
        resources :debrief_ratings
      end
      resources :outcomes do
        resources :check_in_ratings
      end
    end
    resources :memberships, only: %i[new create index destroy]
    resources :milestones
    resources :offers, only: %i[show book] do
      get :book, to: 'support_requests#new'
      resources :support_requests, only: %i[new create]
    end
    resources :topics, only: %i[show index]
  end
  resources :cohorts, only: %i[show index]

  # Statics

  get 'privacy', to: 'statics#privacy'
  get 'terms', to: 'statics#terms'
  get 'home', to: 'statics#home'

  # Root

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  root to: 'statics#home'
end

app/models/membership.rb
# frozen_string_literal: true

class Membership < ApplicationRecord
  attr_accessor :email, :full_name

  belongs_to :project
  belongs_to :user

  enum role: { contributor: 0, stakeholder: 1, mentor: 2 }

  validates :role, presence: true
  validates :project, uniqueness: {
    scope: :user, message: 'this email has already been added to the project'
  }

  validate :display_duplicate_email_error

  def save_with_user
    lookup = find_or_create_user
    if lookup.persisted?
      self.user = lookup
      save
    end
  end

  private

  def display_duplicate_email_error
    errors.add(:email, errors[:project].first) if errors[:project].any?
  end

  def find_or_create_user
    lookup = User.find_or_initialize_by(email: email&.strip)

    if lookup.new_record?
      lookup.full_name = full_name
      lookup.password = SecureRandom.urlsafe_base64

      unless lookup.save
        errors.add(:full_name, lookup.errors[:full_name].first)
        errors.add(:email, lookup.errors[:email].first)
      end
    end

    lookup
  end
end

app/controllers/memberships_controller.rb
# frozen_string_literal: true

class MembershipsController < ApplicationController
  before_action :authenticate_user!, :load_project, :authorise_user

  def index
    redirect_to share_project_path(@project)
  end

  def show
    memberships = Membership.joins(:user).where(project: @project).select(
      'memberships.*', 'users.full_name AS user_full_name', 'users.email AS user_email'
    )
    @contributors = memberships.select { |m| m.role == 'contributor' }
    @stakeholders = memberships.select { |m| m.role == 'stakeholder' }
    @mentors = memberships.select { |m| m.role == 'mentor' }
  end

  def new
    @membership = @project.memberships.new(role: params[:role] || 'contributor')
  end

  def create
    @membership = @project.memberships.new(membership_params)

    if @membership.save_with_user
      NotificationsMailer.project_invite(@membership, current_user).deliver_now
      redirect_to share_project_path(@project), notice: "#{@membership.role.titleize} added"
    else
      render :new
    end
  end

  def destroy
    @membership = Membership.find(params[:id])
    notice = "#{@membership.role.titleize} removed"
    removing_current_user = @membership.user == current_user
    @membership.destroy
    if removing_current_user
      redirect_to projects_path, notice: 'You have been removed from the project'
    else
      redirect_to share_project_path(@project), notice: notice
    end
  end

  private

  def authorise_user
    membership = Membership.find_by(project: @project, user: current_user)
    authorize membership, policy_class: MembershipPolicy
  end

  def membership_params
    params.require(:membership).permit(:email, :full_name, :role)
  end
end

app/views/memberships/new.html.erb
  <%= render partial: 'projects/subnav' %>

<div class="max-w-3xl mx-auto px-4 my-8">
  <p class="mb-6"><%= link_to '‹ Back', share_project_path(@project), class: 'underline' %></p>
  <div class="card">
    <h1 class="text-2xl font-bold mb-6">Add <%= @membership.role %></h1>

    <%= simple_form_for([@project, @membership]) do |f| %>
      <%= f.input :full_name %>
      <%= f.input :email %>
      <%= f.hidden_field :role, value: @membership.role %>
      <p class="text-sm text-gray-600 mb-2">This person will be notified by email.</p>
      <%= f.submit 'Add to project', class: 'btn btn-primary', data: { disable_with: 'Adding...' } %>
    <% end %>
  </div>
</div>

app/views/memberships/show.html.erb
<%= render partial: 'projects/subnav' %>

<div class="max-w-3xl mx-auto px-4 my-8">
  <%= render partial: 'layouts/notices' %>

  <div class="card">
    <h1 class="text-2xl font-bold mb-6">Share project</h1>

    <h2 class="text-lg font-bold mb-2">Contributors</h2>
    <p class="text-sm text-gray-600">These are the people who are responsible for achieving the outcomes we intend. Contributors can create and edit all items in a project, including modifying the projects details and its members. Contributors receive reminders and are notified when check-ins and debriefs are completed or overdue.</p>

    <hr class="my-4">

    <%- @contributors.each do |membership| %>
      <%#TODO:= current_user.email == membership.user_email ? '[Your membership]' : '' %>
      <%= membership.user_full_name %>
      (<%= membership.user_email %>)
      <%#TODO:= membership.user.last_sign_in_at.nil? ? 'Inactive' : 'Active' %>
      <%= link_to 'Remove', project_membership_path(@project, membership), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-sm text-red-600 underline hover:text-red-700' %>
      <hr class="my-4">
    <% end %>

    <div class="mb-8">
      <%= link_to 'Add contributor', new_project_membership_path(@project, role: 'contributor'), class: 'link' %>
    </div>

    <h3 class="text-lg font-bold mb-2">Stakeholders</h3>
    <p class="text-sm text-gray-600">These are the people who needs to be consulted with or informed about the outcomes we intend. Stakeholders can view all items in a project and some of its details, but cannot modify its members or see check-ins. Stakeholders are notified when debriefs are completed.</p>

    <hr class="my-4">

    <%- @stakeholders.each do |membership| %>
      <%#TODO:= current_user.email == membership.user_email ? '[Your membership]' : '' %>
      <%= membership.user_full_name %>
      (<%= membership.user_email %>)
      <%#TODO:= membership.user.last_sign_in_at.nil? ? 'Inactive' : 'Active' %>
      <%= link_to 'Remove', project_membership_path(@project, membership), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-sm text-red-600 underline hover:text-red-700' %>
      <hr class="my-4">
    <% end %>

    <div class="mb-1">
      <%= link_to 'Add stakeholder', new_project_membership_path(@project, role: 'stakeholder'), class: 'link' %>
    </div>

    <%- if @mentors.any? %>
      <h3 class="text-lg font-bold mt-8 mb-2">Mentors</h3>
      <p class="text-sm text-gray-600">Mentors have the same permissions as contributors along with some additional capabilities to help them support teams. Mentors are notified when check-ins and debriefs are completed or overdue.</p>

      <hr class="my-4">

      <%- @mentors.each do |membership| %>
        <%#TODO:= current_user.email == membership.user_email ? '[Your membership]' : '' %>
        <%= membership.user_full_name %>
        (<%= membership.user_email %>)
        <hr class="my-4">
      <% end %>
    <% end %>
  </div>
</div>