config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Sessions

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Core application routes

  resources :projects, except: :destroy do
    member do
      get :about
      get :share, to: 'memberships#show'
    end
    # TODO: https://guides.rubyonrails.org/routing.html#limits-to-nesting
    resources :iterations do
      resources :check_ins do
        resources :check_in_ratings
      end
      resources :debriefs do
        resources :debrief_ratings
      end
      resources :outcomes do
        resources :check_in_ratings
      end
    end
    resources :memberships, only: %i[new create index destroy]
    resources :milestones
    resources :offers, only: %i[show book] do
      get :book, to: 'support_requests#new'
      resources :support_requests, only: %i[new create]
    end
    resources :topics, only: %i[show index]
  end
  resources :cohorts, only: %i[show index]

  # Statics

  get 'privacy', to: 'statics#privacy'
  get 'terms', to: 'statics#terms'
  get 'home', to: 'statics#home'

  # Root

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  root to: 'statics#home'
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_and_belongs_to_many :offers
  
  validates :title, :short_desc, :long_desc, presence: true
end

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  before_action :authenticate_user!, :load_project

  def index
    @topics = @project.topics.uniq.sort_by(&:title)

    return unless @topics.empty?

    flash[:alert] = "Sorry, you don't have access to that"
    redirect_back(fallback_location: root_path)
  end

  def show
    @topic = Topic.find(params[:id])
    @offers = @topic.offers & @project.offers

    return if @project.topics.include?(@topic)

    flash[:alert] = "Sorry, you don't have access to that"
    redirect_back(fallback_location: root_path)
  end
end

app/views/topics/index.html.erb
<%= render partial: 'projects/subnav' %>

<div class="max-w-5xl container mx-auto px-4 my-8">
  <div class="mx-4 "><%= render partial: 'layouts/notices' %></div>

  <h1> Get help with your project </h1>
  <div class="md:flex my-8">
    <div class="flex-none md:max-w-xs mb-8 mr-8">
      <h3 class="mb-2">Categories</h3>
      <ul>
        <% @topics.each do |topic| %>
          <li class="mb-1"><%= link_to topic.title, '#' + topic.title.parameterize, class: 'link' %></li>
        <% end %>
      </ul>
    </div>
    <div class="flex-1">
      <div class="flex flex-wrap items-start justify-between">
        <% @topics.each do |topic| %>
          <div class="w-1/2 flex self-stretch">
            <div class="w-full ml-12 mb-12 border-2 border-gray-300 flex flex-col bg-white">
              <div class="bg-gray-400 px-6 py-4">
                <h1 id="<%= topic.title.parameterize %>"><%= topic.title %></h1>
              </div>
              <div class="p-6">
                <p><%= topic.short_desc %></p>
              </div>
              <div class="p-6 pt-0 mt-auto">
                <p class="mt-auto"><%= link_to 'Find out more', project_topic_path(@project, topic), class: 'link' %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <% unless @project.members('mentor').empty? %>
      <div class="mx-12">
        <p>If the support you're looking for isn't listed here, get in touch with your coach <%= @project.members('mentor')[0].full_name %>.</p>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<%= render partial: 'projects/subnav' %>

<div class="max-w-3xl mx-auto px-4 my-8">
  <p class="mb-6"><%= link_to '‹ Back', project_topics_path(@project), class: 'underline' %></p>
  <%= render partial: 'layouts/notices' %>

  <div class="card mb-3">
      <h1><%= @topic.title %></h1>
      <div class="rich-text border-none p-0 my-3">
        <%= @topic.long_desc&.html_safe %>
      </div>

      <% @offers.group_by(&:duration_category).each do |category, offers| %>
        <h2 class="mt-12 mb-3"><%= category %></h2>
        <% offers.each do |offer| %>
          <div>
            <h3 class="mb-3"><%= offer.title %></h3>
            <div class="mb-6">
              <p>Provided by: <%= link_to offer.provider.name, offer.provider.website, class: 'link', target: '_blank' %></p>
              <p>Duration: <%= offer.duration_description %></p>
            </div>
           
            <div class="rich-text border-none p-0 mb-5">
              <%= offer.short_description&.html_safe %>
            </div>

            <%= link_to 'Find out more', project_offer_path(@project, offer), class: 'btn bg-orange-500 hover:bg-orange-600 text-white my-6' %>
            <hr class="my-6">
          </div>
        <% end %>
      <% end %>
  </div>
</div>