config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Sessions

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Core application routes

  resources :projects, except: :destroy do
    member do
      get :about
      get :share, to: 'memberships#show'
    end
    # TODO: https://guides.rubyonrails.org/routing.html#limits-to-nesting
    resources :iterations do
      resources :check_ins do
        resources :check_in_ratings
      end
      resources :debriefs do
        resources :debrief_ratings
      end
      resources :outcomes do
        resources :check_in_ratings
      end
    end
    resources :memberships, only: %i[new create index destroy]
    resources :milestones
    resources :offers, only: %i[show book] do
      get :book, to: 'support_requests#new'
      resources :support_requests, only: %i[new create]
    end
    resources :topics, only: %i[show index]
  end
  resources :cohorts, only: %i[show index]

  # Statics

  get 'privacy', to: 'statics#privacy'
  get 'terms', to: 'statics#terms'
  get 'home', to: 'statics#home'

  # Root

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  root to: 'statics#home'
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :cohort, optional: true
  has_many :offers, through: :cohort
  has_many :topics, through: :offers

  has_many :iterations, dependent: :destroy
  has_many :milestones, dependent: :destroy

  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  has_many :support_requests, dependent: :destroy

  validates :description, :title, presence: true

  audited
  
  def members(roles = %w[contributor mentor stakeholder])
    @memberships = self.users.joins(:memberships).where(memberships: {role: roles})
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_project, except: :index

  def index
    @projects = current_user.projects.order(title: :desc)
                            .select('projects.*', 'memberships.role')

    @contributor = @projects.select { |p| p.role == Membership.roles['contributor'] }
    @stakeholder = @projects.select { |p| p.role == Membership.roles['stakeholder'] }
    @mentor = @projects.select { |p| p.role == Membership.roles['mentor'] }

    @other_projects = current_user.is_admin? ? Project.all - @projects : []
  end

  def show
    authorize @project, policy_class: ProjectPolicy
  end

  def new
    @project = authorize Project.new
  end

  def create
    @project = authorize Project.new(project_params)
    @project.users << current_user

    if @project.save
      @project.milestones.create(Milestone::PRESETS)
      redirect_to project_path(@project), notice: 'Welcome to your new project!'
    else
      render :new
    end
  end

  def edit
    authorize @project, policy_class: ProjectPolicy
  end

  def update
    authorize @project

    if @project.update(project_params)
      redirect_to about_project_path(@project)
    else
      render :edit
    end
  end

  def about
    authorize @project, policy_class: ProjectPolicy
  end

  private

  def project_params
    params.require(:project).permit(:description, :more_details, :title)
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>

  <%= f.input :title, input_html: { class: 'w-full'} %>
  <%= f.input :description, input_html: { class: 'w-full', rows: 3 } %>

  <%- if %w[edit update].include?(action_name) %>
    <%= f.input :more_details, as: :trix_editor %>
  <% end %>

  <%- if %w[new create].include?(action_name) %>
    <label class="block text-gray-600">
      <input class="mr-1" type="checkbox" checked="checked" disabled="disabled">
      <span>Include default milestones</span>
    </label>
  <% end %>

  <%= f.submit class: 'btn btn-primary mt-6', data: { disable_with: 'Saving...' } %>

<% end %>

app/views/projects/_subnav.html.erb
<div class="bg-primary-700">
  <div class="flex items-center justify-between flex-wrap pt-3 px-4 max-w-5xl container mx-auto">
    <h2 class="text-white mb-1 mr-6 md:w-1/2 md:truncate" ><%= link_to @project.title, project_path(@project), class: 'hover:opacity-75' %></h2>
    <nav>
      <ul class="flex sm:mt-0 mt-4">
        <li>
          <%= link_to 'Roadmap', project_path(@project), class: "tab #{active_tab?(controller: 'projects', action: 'show')}" %>
        </li>
        <li class="ml-1">
          <%= link_to 'About', about_project_path(@project), class: "tab #{active_tab?(controller: 'projects', action: 'about')}" %>
        </li>
        <li class="ml-1">
          <%= link_to 'Share', share_project_path(@project), class: "tab #{active_tab?(controller: 'memberships')}" %>
        </li>
        <% unless @project.topics.empty? %>
          <li class="ml-1">
            <%= link_to 'Get support', project_topics_path(@project), class: "tab #{active_tab?(controller: 'topics') || active_tab?(controller: 'offers') || active_tab?(controller: 'support_requests')}" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/projects/about.html.erb
<%= render partial: 'subnav' %>

<div class="max-w-3xl mx-auto px-4 my-8">

  <%= render partial: 'layouts/notices' %>

  <div class="card">
    <div class="flex items-end items-center justify-between mb-6">
      <h1 class="text-2xl font-bold">About project</h1>
      <%= link_to 'Edit', edit_project_path(@project), class: 'link' %>
    </div>

    <p class="mb-2"><strong>Goal</strong></p>
    <p class="mb-6"><%= @project.description %></p>

    <p class="mb-2"><strong>More about the project</strong></p>
    <%- if @project.more_details.blank? %>
      <p class="italic text-gray-600">Not provided</p>
    <% else %>
      <div class="rich-text"><%= @project.more_details&.html_safe %></div>
    <% end %>
  </div>
</div>

app/views/projects/assumptions.html.erb
<%= render "projects/header" %>

<% if policy(@project.assumptions.new).new? %>
  <%= link_to new_project_assumption_path(@project), class: 'mb-4 btn btn-info btn-icon' do %>
    Add card
  <% end %>
<% end %>

<% if @project.assumptions.count > 0 %>

  <div class="row">
    <% @assumptions.each do |assumption| %>
      <div class="col-md-12">
        <%= render partial: 'assumptions/card', locals: { description: false, edit: false, assumption: assumption } %>
      </div>
    <% end %>
  </div>

  <%= paginate @assumptions %>

<% else %>

  <div class="bg-light rounded text-center p-5 mt-4">
    <p class='lead mb-4'>Add some assumptions to get started.</p>
    <%= link_to new_project_assumption_path(@project), class: 'btn btn-info btn-icon' do %>
      <em class="fa fa-comment-medical"></em>
      Add assumption
    <% end %>
  </div>

<% end %>

app/views/projects/edit.html.erb
<div class="max-w-3xl mx-auto px-4 my-8">
  <p class="mb-6"><%= link_to '‹ Back', about_project_path(@project), class: 'underline' %></p>
  <div class="card">
    <h1 class="text-2xl font-bold mb-6">Edit project</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="max-w-3xl mx-auto px-4 my-8">
  <%= render partial: 'layouts/notices' %>

  <div class="flex items-center justify-between">
    <h1>Projects</h1>
    <%= link_to 'New project', new_project_path(), class: "btn btn-primary" %>
  </div>

  <% if @projects.any? %>

    <%- if @contributor.any? %>
      <hr class="my-6">
      <h2>Contributor</h2>
      <% @contributor.each do |project| %>
        <div class="card mt-3">
          <h3 class="text-lg font-bold mb-4"><%= link_to project.title, project_path(project), class: 'link' %></h3>
          <%= project.description %>
        </div>
      <% end %>
    <% end %>

    <%- if @stakeholder.any? %>
      <hr class="my-6">
      <h2>Stakeholder</h2>
      <% @stakeholder.each do |project| %>
        <div class="card mt-3">
          <h3 class="text-lg font-bold mb-4"><%= link_to project.title, project_path(project), class: 'link' %></h3>
          <%= project.description %>
        </div>
      <% end %>
    <% end %>

    <%- if @mentor.any? %>
      <hr class="my-6">
      <h2>Mentor</h2>
      <% @mentor.each do |project| %>
        <div class="card mt-3">
          <h3 class="text-lg font-bold mb-4"><%= link_to project.title, project_path(project), class: 'link' %></h3>
          <%= project.description %>
        </div>
      <% end %>
    <% end %>

  <% else %>

    <div class="text-center">
      <h2 class="text-lg font-bold mt-16 mb-4">No projects</h2>
      <%= link_to 'Create your first', new_project_path, class: "link" %>
    </div>

  <% end %>
  
  <% if @other_projects.any? %>
      <hr class="my-6">
      <h2>All Other Projects</h2>
      <% @other_projects.each do |project| %>
        <div class="card mt-3">
          <h3 class="text-lg font-bold mb-4"><%= link_to project.title, project_path(project), class: 'link' %></h3>
          <%= project.description %>
        </div>
      <% end %>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="max-w-3xl mx-auto px-4 my-8">
  <p class="mb-6"><%= link_to '‹ Back', projects_path, class: 'underline' %></p>
  <div class="card">
    <h1 class="text-2xl font-bold mb-6">New project</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/projects/show.html.erb
<%# TODO: refactor! %>
<script type="text/javascript">
  $(function(){

    $('#roadmap .row.completed ').hide();

    $('a[data-status]').on('click', function(){
      var status = $(this).data('status');
      $('#statuses li').removeClass('active');
      $(this).parents('li').addClass('active');

      if(status == 'all'){
        $('#roadmap .row ').show();
      }else if(status == 'default'){
        $('#roadmap .row ').hide();
        $('#roadmap .row.planned').show();
        $('#roadmap .row.committed').show();
      }else{
        $('#roadmap .row ').hide();
        $('#roadmap .row.'+status).show();
      }
      $('#roadmap .row.start').show();

    });

  });
</script>

<%# TODO: refactor end %>

<%= render partial: 'subnav' %>

<div class="max-w-5xl container mx-auto">
  <div class="mx-4 "><%= render partial: 'layouts/notices' %></div>

  <div class="md:flex my-8">

    <div class="flex-none w-full md:max-w-xs px-4 mb-8">
      <%= link_to 'New iteration', new_project_iteration_path(@project), class: 'btn btn-primary block w-full text-center mb-8' %>
      <h3 class="mb-3">Status</h3>
      <ul id="statuses" class="text-primary-600">
        <li class="active mb-3">
          <a data-status="default">
            Default
            <br>
            <span class="text-sm text-gray-600">Committed &amp; Planned</span>
          </a>
        </li>
        <li class="mb-3">
          <a data-status="all">All</a>
        </li>
        <li class="mb-3">
          <a data-status="completed">Completed</a>
        </li>
        <li class="mb-3">
          <a data-status="committed">Committed</a>
        </li>
        <li class="mb-3">
          <a data-status="planned">Planned</a>
        </li>
      </ul>

    </div>

    <div class="flex-1 mb-8 ml-8 mr-4">
      <%# TODO: refactor! %>
      <div id="roadmap">
        <%
        merged = [];

        #Get iterations
        @project.iterations.each do |iteration|
          merged << {
            :type       => 'iteration',
            :status     => iteration.status,
            :status_num => Iteration.statuses[iteration.status],
            :start_date => iteration.start_date || Date.tomorrow,
            :end_date   => iteration.debrief_date || Date.tomorrow,
            :data       => iteration
          }
        end

        #Get milestones
        @project.milestones.each do |milestone|
          merged << {
            :type       => 'milestone',
            :status   	=> milestone.status,
            :status_num	=> Milestone.statuses[milestone.status],
            :start_date => milestone.deadline || Date.tomorrow,
            :data       => milestone
          }
        end

        #Sort the merged array reverse chronologically
        items = merged.sort_by { |hsh| [-hsh[:status_num], hsh[:start_date]] }
        old_status = '';
        items.each_with_index do |item|

          if item[:status] != old_status
          %>
            <div class='row divider <%= item[:status].parameterize %>'>
              <div>
                <span class='tag rounded-t-none <%= item[:status].parameterize %>'><%= item[:status].titleize %></span>
              </div>
            </div>
          <%
            old_status = item[:status]
          end

          if item[:type] == 'iteration'
            iteration = item[:data]
          %>

            <div class='row iteration <%= iteration.status %> '>
              <div class='card w-full'>
                <h3>Iteration: <%= link_to iteration.title, [@project, iteration], class: 'underline hover:opacity-75' %></h3>
                <p class="mb-6"><%= iteration.description %></p>

                <% if iteration.status_planned? %>
                  <% if iteration.start_date? %>
                    <p>Planning to start <%= friendly_date(iteration.start_date) %></p>
                  <% else %>
                    <p class="missing-text">No updates yet</p>
                  <% end %>

                <% elsif iteration.status_committed? %>
                  <h3>Latest update</h3>

                  <% if !current_user.is_admin? && current_user.memberships.find_by(project: @project).role == 'stakeholder' %>
                    <% #Stakeholders can just see how many check-ins have been done %>

                    <% if check_ins = iteration.check_ins.count %>
                      <p>Completed <%= pluralize(check_ins, 'check-in') %></p>
                    <% else %>
                      <p class="missing-text">No updates yet</p>
                    <% end %>

                  <% else %>
                    <% #Mentors and contributors can see warnings, and links to all check-ins %>

                    <% if iteration.warning == :check_in_due || iteration.warning == :debrief_due %>
                      <%= render_warning(iteration.warning, iteration) %>
                    <% end %>

                    <% if check_in = iteration.check_ins.last %>
                      <p><%= link_to 'Checked in on '+friendly_date(check_in.created_at), [@project, iteration, check_in], class: 'link' %> - <%= render_check_in_status(check_in) %></p>
                    <% else %>
                      <p class="missing-text">No updates yet</p>
                    <% end %>

                  <% end %>

                <% end %>

                <% #Everyone can see information about debriefs %>
                <% if iteration.status_completed? %>
                  <p class="mt-6">Debrief completed on <%= link_to friendly_date(iteration.debrief.created_at), [@project, iteration, iteration.debrief], class: 'link' %></p>
                <% elsif iteration.status_committed? %>
                  <p class="mt-6">Debrief due on <%= friendly_date(iteration.debrief_date) %></p>
                <% elsif iteration.status_planned? && iteration.debrief_date %>
                  <p class="mt-6">Debrief planned for <%= friendly_date(iteration.debrief_date) %></p>
                <% end %>

              </div>
            </div>
          <%
          elsif item[:type] == 'milestone'
            milestone = item[:data]
          %>
            <div class='row milestone <%= milestone.status %>'>
              <div>
                <h3 class="mb-2">Milestone: <%= link_to milestone.title, project_milestone_path(@project, milestone), class: 'underline hover:opacity-75' %></h3>
                <p class="mb-2"><%= milestone.description%></p>
                <% if milestone.completed_at? %>
                  <b class="text-sm text-gray-600"><%= friendly_date(milestone.completed_at) %></b>
                <% else %>
                  <b class="text-sm text-gray-600">By <%= milestone.deadline.strftime("%b %Y") %></b>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class='row start'>
          <div>
            <p>Add an <%= link_to 'iteration', new_project_iteration_path(@project), class: 'link' %> or <%= link_to 'milestone', new_project_milestone_path(@project), class: 'link' %></p>
          </div>
        </div>
      </div>
      <%# TODO: refactor end %>

    </div>
  </div>
</div>