config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Sessions

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Core application routes

  resources :projects, except: :destroy do
    member do
      get :about
      get :share, to: 'memberships#show'
    end
    # TODO: https://guides.rubyonrails.org/routing.html#limits-to-nesting
    resources :iterations do
      resources :check_ins do
        resources :check_in_ratings
      end
      resources :debriefs do
        resources :debrief_ratings
      end
      resources :outcomes do
        resources :check_in_ratings
      end
    end
    resources :memberships, only: %i[new create index destroy]
    resources :milestones
    resources :offers, only: %i[show book] do
      get :book, to: 'support_requests#new'
      resources :support_requests, only: %i[new create]
    end
    resources :topics, only: %i[show index]
  end
  resources :cohorts, only: %i[show index]

  # Statics

  get 'privacy', to: 'statics#privacy'
  get 'terms', to: 'statics#terms'
  get 'home', to: 'statics#home'

  # Root

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  root to: 'statics#home'
end

app/models/iteration.rb
# frozen_string_literal: true

class Iteration < ApplicationRecord
  belongs_to :project

  has_many :check_ins, dependent: :destroy
  has_one :debrief, dependent: :destroy

  has_many :outcomes, dependent: :destroy
  accepts_nested_attributes_for :outcomes, allow_destroy: true

  enum status: { planned: 0, committed: 1, completed: 2 }, _prefix: :status

  validates :title, presence: true
  validates :start_date, :planned_debrief_date, presence: true, if: :status_committed?
  validates :outcomes, length: {
    minimum: 1, maximum: 5, message: 'You must have between 1 and 5 outcomes defined'
  }, if: :status_committed?

  validate :cannot_be_longer_than_12_weeks
  validate :cannot_be_shorter_than_2_weeks
  validate :debrief_date_cannot_be_before_start_date

  audited

  def debrief_date
    actual_debrief_date || planned_debrief_date
  end

  def draftable?
    status_planned? || status_changed?(from: 'planned', to: 'committed')
  end

  def warning(check_in_gap: -14, debrief_gap: 4)
    return unless status_committed?

    return :check_in_due if check_in_distance <= check_in_gap && debrief_distance > debrief_gap

    return :debrief_due if debrief_distance.negative?
  end

  private

  def cannot_be_longer_than_12_weeks
    return if dates_missing?

    errors.add(:planned_debrief_date, "iteration can't be longer than 12 weeks") if number_of_weeks >= 12
  end

  def cannot_be_shorter_than_2_weeks
    return if dates_missing?

    errors.add(:planned_debrief_date, "iteration can't be shorter than 2 weeks") if number_of_weeks < 2
  end

  def check_in_date
    last_check_in_at&.to_date || start_date
  end

  def check_in_distance
    (check_in_date - Time.zone.today).to_i
  end

  def dates_missing?
    planned_debrief_date.nil? || start_date.nil?
  end

  def debrief_date_cannot_be_before_start_date
    return if dates_missing?

    errors.add(:planned_debrief_date, "can't be before start date") if planned_debrief_date < start_date
  end

  def debrief_distance
    (planned_debrief_date - Time.zone.today).to_i
  end

  def number_of_weeks
    (planned_debrief_date - start_date).to_i / 7
  end
end

app/controllers/iterations_controller.rb
# frozen_string_literal: true

class IterationsController < ApplicationController
  before_action :load_project

  def index
    redirect_to project_url(@project)
  end

  def new
    @iteration = authorize @project.iterations.new
  end

  def create
    @iteration = authorize @project.iterations.new(iteration_params)

    if @iteration.save
      redirect_to project_iteration_url(@project, @iteration), notice: msg(@iteration.draftable?)
    else
      render :new
    end
  end

  def show
    @iteration = authorize @project.iterations.find(params[:id])
  end

  def edit
    @iteration = authorize @project.iterations.find(params[:id])
  end

  def update
    @iteration = authorize @project.iterations.find(params[:id])

    if @iteration.update(iteration_params)
      redirect_to project_iteration_url(@project, @iteration), notice: msg(@iteration.draftable?)
    else
      render :edit
    end
  end

  def destroy
    @iteration = authorize Iteration.find(params[:id])
    @iteration.destroy

    @project = Project.find(params[:project_id])
    redirect_to project_path(@project), notice: 'Draft iteration deleted.'
  end

  private

  def iteration_params
    params.require(:iteration).permit(
      :title, :description, :start_date, :planned_debrief_date, :status,
      outcomes_attributes: %i[id title success_criteria _destroy]
    )
  end

  def msg(draftable)
    {
      true => 'Iteration saved as draft.',
      false => "Iteration saved. You'll receive reminders to " \
               'check-in every two weeks from the start date.'
    }[draftable]
  end
end

app/helpers/iterations_helper.rb
# frozen_string_literal: true

module IterationsHelper
  def mentor_membership
    Membership.find_by(project: @iteration.project, user: current_user, role: :mentor)
  end

  def render_warning(key, iteration)
    case key
    when :check_in_due
      tag.div class: 'notice danger my-4' do
        tag.span('Over two weeks since last check in. ') +
          tag.a('Add a check-in', href: new_project_iteration_check_in_path(iteration.project, iteration), class: 'link')
      end
    when :debrief_due
      tag.div(class: 'notice danger my-4') do
        tag.span('Debrief overdue. ') +
          tag.a('Add a debrief', href: new_project_iteration_debrief_path(iteration.project, iteration), class: 'link')
      end
    end
  end
end

app/views/iterations/_form.html.erb
<%= simple_form_for([@project, @iteration]) do |f| %>

  <%= f.input :title, input_html: { class: 'w-full' } %>

  <%= f.input :description, input_html: { class: 'w-full', rows: 3 } %>

  <div class="mb-6" id="outcomes">
    <h2>Outcomes</h2>

    <p class="hint mb-4">Between 1 and 5 outcomes that you'll work towards in this iteration.</p>
    <%= f.error :outcomes, class: 'text-sm text-red-600' %>
    <%= f.simple_fields_for :outcomes, f.object.outcomes.sort_by{|o| o.created_at} do |outcome| %>
      <%= render 'outcome_fields', f: outcome %>
    <% end %>
  </div>

  <%- if mentor_membership || @iteration.draftable? %>
    <div class='mb-6'>
      <%= link_to_add_association 'Add outcome', f, :outcomes, class: 'link', data: { association_insertion_node: '#outcomes', association_insertion_method: :append } %>
    </div>
  <% end %>

  <%- if @iteration.status_completed? %>
    <div class="mb-4">
      <p><strong>Start date</strong></p>
      <p><%= friendly_date(@iteration.start_date) %></p>
    </div>
    <div class="mb-4">
      <p><strong>Debrief date</strong></p>
      <p><%= friendly_date(@iteration.debrief_date) %></p>
    </div>
  <% else %>
    <%= f.input :start_date, html5: true, input_html: { placeholder: 'yyyy-mm-dd' } %>
    <%= f.input :planned_debrief_date, html5: true, input_html: { placeholder: 'yyyy-mm-dd' } %>
  <% end %>

  <%- if @iteration.draftable? %>
    <%= f.button :button, 'Commit to iteration', type: 'submit', name: 'iteration[status]', value: 'committed', class: 'btn-primary mr-1 mt-2', data: { disable_with: 'Saving...', confirm: "Outcomes cannot be changed and you'll receive regular reminders to check-in from the start date once you commit to this iteration. Are you ready to commit?" } %>
  <% else %>
    <%= f.submit class: 'btn btn-primary mt-2', data: { disable_with: 'Saving...' } %>
  <% end %>

  <%- if @iteration.draftable? %>
    <%= f.button :button, 'Save as draft', type: 'submit', name: 'iteration[status]', value: 'planned', class: 'bg-gray-200 mt-2', data: { disable_with: 'Saving...' } %>
  <% end %>
<% end %>

app/views/iterations/_outcome_fields.html.erb
<div class="card mb-4 nested-fields">
  <%= f.input :title, input_html: { class: 'w-full' } %>
  <%= f.input :success_criteria, input_html: { class: 'w-full' } %>
  <%= link_to_remove_association "Remove outcome", f, class: 'link' %>
</div>

app/views/iterations/edit.html.erb
<%= render partial: 'projects/subnav' %>

<div class="max-w-3xl mx-auto px-4 my-8">
  <p class="mb-6"><%= link_to '‹ Back', project_iteration_path(@project, @iteration), class: 'underline' %></p>
  <%= render partial: 'layouts/notices' %>

  <div class="card">
    <h1 class="text-2xl font-bold mb-6">Edit iteration</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/iterations/new.html.erb
<%= render partial: 'projects/subnav' %>

<div class="max-w-5xl mx-auto px-4 my-8">
  <p class="mb-6"><%= link_to '‹ Back to roadmap', project_path(@project), class: 'underline' %></p>

  <div class="md:flex flex-col md:flex-row-reverse">
    <div class="p-6 border-2 border-gray-300 text-gray-700 rounded-sm flex-1 mb-6 md:max-w-xs md:self-start">
      <h3 class="mb-3">What is an iteration?</h3>
      <p class="mb-3">You can think of an iteration as a short and very focused project.</p>
      <p class="mb-3">Usually between 2-12 weeks long - it involves a team, a deadline and a set of outcomes to work towards.</p>
      <p class="mb-3">By working in small batches it's easier to respond to new information and limit the risk of trying new ideas or making mistakes.</p>
      <p>Because of this, an iteration isn't complete until the team has reflected on what they've learnt and decided on what steps to take next - often another iteration.</p>
    </div>

    <div class="card flex-1 md:mr-6">
      <h1 class="mb-6">New iteration</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/iterations/show.html.erb
<%= render partial: 'projects/subnav' %>

<div class="max-w-3xl mx-auto px-4 my-8">
  <p class="mb-6"><%= link_to '‹ Back to roadmap', project_path(@project), class: 'underline' %></p>
  <%= render partial: 'layouts/notices' %>

  <div class="card">
    <div class="flex items-end items-center justify-between mb-3">
      <h1><%= @iteration.title %></h1>
      <div>
		  <%= link_to 'Edit', edit_project_iteration_path(@project, @iteration), class: 'link' %>
		  <% if @iteration.status_planned? %>
			  <%= link_to 'Delete', project_iteration_path(@project, @iteration), class: 'link', data: {:confirm => 'Are you sure?'}, method: :delete %>
		  <% end %>
      </div>
    </div>

    <div class="mb-6">
      <span class="tag <%= @iteration.status.parameterize %>"><%= @iteration.status.titleize %></span>
    </div>

    <div class="mb-6">
      <%= with_default(@iteration.description, text: 'Description not provided', formatter: :simple_format) %>
    </div>
    
    <div class="mb-6">
      <h2 class="mb-4"><%= @iteration.status_planned? ? 'Plan' : 'Progress' %></h2>
      <%= render_warning(@iteration.warning, @iteration) %>
      <hr>

      <div class="flex flex-wrap mt-3">
        <div class="w-full sm:w-1/4 mb-3">Start</div>
        <div class="w-full sm:w-3/4 mb-3">
          <%= with_default(@iteration.start_date, formatter: :friendly_date) %>
        </div>
      </div>
      <hr>

      <% if @iteration.status_committed? %>
        <div class="flex flex-wrap mt-3 missing-text">
          <div class="w-full sm:w-1/4 mb-3">Check-ins</div>
          <div class="w-full sm:w-3/4 mb-3">
            Every two weeks
            <% if policy(@iteration).create? %>
              <small>(Only visible to project contributors)</small>
            <% end %>
          </div>
        </div>
        <hr>
      <% end %>

      <% if policy(@iteration).create? %>
        <% @iteration.check_ins.each do |check_in| %>
          <div class="flex flex-wrap mt-3">
            <div class="w-full sm:w-1/4 mb-3"><%= link_to 'Check-in', [@iteration.project, @iteration, check_in], class: 'link' %></div>
            <div class="w-full sm:w-3/4 mb-3">
              <%= friendly_date(check_in.updated_at) %> - <%= render_check_in_status(check_in) %>
            </div>
          </div>
          <hr>
        <% end %>
      <% end %>

      <div class="flex flex-wrap mt-3">
        <% if @iteration.debrief %>
          <div class="w-full sm:w-1/4 mb-3">
            <%= link_to 'Debrief', [@project, @iteration, @iteration.debrief], class: 'link' %>
          </div>
          <div class="w-full sm:w-3/4 mb-3">
            <%= with_default(@iteration.debrief_date, formatter: :friendly_date) %>
          </div>
        <% elsif @iteration.status_committed? %>
          <div class="w-full sm:w-1/4 mb-3">
            Debrief
          </div>
          <div class="w-full sm:w-3/4 mb-3">
            Due <%= with_default(@iteration.planned_debrief_date, formatter: :friendly_date) %>
          </div>
        <% else %>
          <div class="w-full sm:w-1/4 mb-3">
            Debrief
          </div>
          <div class="w-full sm:w-3/4 mb-3">
            <%= with_default(@iteration.planned_debrief_date, formatter: :friendly_date) %>
          </div>
        <% end %>
      </div>
      <hr>
    </div>

    <h2>Outcomes</h2>
    <% if !@iteration.outcomes.any? %>
      <p class="missing-text mt-2">You've not added any outcomes yet.</p>
    <% else %>
      <p class="hint">What we want to have achieved by the end of this batch of work.</p>
      <% @iteration.outcomes.order(:created_at).each do |outcome| %>
        <div class='inner-card mt-4'>
          <p><strong>What are we going to learn or prove?</strong></p>
          <p class="mb-4"><%= outcome.title %></p>
          <p><strong>As a minimum, we’ll know we’ve learnt or proved this when…</strong></p>
          <p><%= outcome.success_criteria %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>